---
title: "A data-driven planning framework for curbside loading zones - exploratory data analysis"
author: " "
date: 2024-01-30
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```


## 1 Introduction

Sam


## 2 Data Manipulation and Visualization





```{r , include=FALSE}

# You can set some global options for knitting chunks

knitr::opts_chunk$set(echo = TRUE)

# Load some libraries

library(tidyverse)
library(tidycensus)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot) # plot correlation plot
library(corrr)      # another way to plot correlation plot
library(kableExtra)
library(broom)
library(tufte)
library(rmarkdown)
library(hexbin)
library(viridis)
library(cbsodataR)
library(jtools)     # for regression model plots
library(ggstance) # to support jtools plots
library(ggpubr)    # plotting R^2 value on ggplot point scatter
library(broom.mixed) # needed for effects plots
library(stargazer)
library(jsonlite)
library(ggplot2)
library(tmap)
library(tmaptools)
library(leaflet)
library(raster)
library(RColorBrewer)
library(mapview)
library(leaflet)
library(plotly)
library(ggspatial)
library(openxlsx)
library(lubridate)

#library(rjson)

# functions and data directory

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette2 <- c('#3E4A89','#1F9E89')
palette4 <- c('#3E4A89','#1F9E89','#35B779','#B4DE2C')
palette5 <- c('#440154','#3E4A89','#1F9E89','#35B779','#B4DE2C')
palette6 <- c('#440154','#3E4A89','#1F9E89','#35B779','#B4DE2C','#FDE725')
palette10 <- c('#440154','#482777','#3E4A89','#31688E','#26828E','#1F9E89','#35B779','#6DCD59','#B4DE2C','#FDE725')

```

```{r setting working directory}
#Shengqian
#setwd("/Users/sqwang/Library/CloudStorage/OneDrive-PennO365/penn/6th/Practicum/Data")

#Sam
#setwd("")

#michael
#setwd("")

#tiffany
#setwd("")

#ling
setwd("/Users/lingchen/Documents/Practicum/Practicum_Philly_2024/Data")


coords_raw <- read.csv("./Old_Data_for_Testing/zoneCoords.csv")
# split coords
coords_split <- strsplit(coords_raw$coords, ",")
coords_raw$latitude <- as.numeric(sapply(coords_split, `[`, 1))
coords_raw$longitude <- as.numeric(sapply(coords_split, `[`, 2))
# create coords shapefile
coords <- st_as_sf(coords_raw, coords = c("longitude", "latitude"), crs = 'ESRI:102729')


linAssets <- read_sf('./resmartloadingzones/Curb_and_Asset_Shapefiles/linear_assets.shp')%>% st_transform('ESRI:102729')
# load booking data
booking_data <-st_read("./Old_Data_for_Testing/Booking Data_cleaned.geojson")

# load curb zone data
curb_zone <-  read_json("./resmartloadingzones/curb_zones.json")

# load CDS event data
event_export <- read.csv("./events_export_CDS.csv")

# load regulation geojson
regulations <- st_read("./resmartloadingzones/regulations.geojson")

# load pilot data
#pre_pilot <- read.xlsx("./PHL_Pre-Pilot NN Collection Data_2022_12.xlsx")
#mid_pilot <- read.xlsx("./PHL_Mid-Pilot NN Collection_2023_02.xlsx")

```

### old data for testing - booking data exploratory analysis
#### Utilization of curb zones
```{r}
utilization <- booking_data %>%
  dplyr::select(OMFCurbZoneID,EventType,ViolationType,VehicleType,TimeRequestedHour,Amount,geometry)

utilization$OMFCurbZoneID <- substr(utilization$OMFCurbZoneID, nchar(utilization$OMFCurbZoneID)-2, nchar(utilization$OMFCurbZoneID))

```

```{r timesegment}
utilization$DwellTimeMinutes <- utilization$TimeRequestedHour * 60

utilization$TimeSegment <- cut(utilization$DwellTimeMinutes,
                        breaks = c(0, 5, 15, 30, 45, 61),
                        labels = c("0-5", "6-15", "16-30", "31-45","46-60"),
                        right = FALSE)

utilization <- utilization %>%
  mutate(TimeSegment = as.character(TimeSegment), # Convert factor to character
         TimeSegment = replace_na(TimeSegment, "violation")) # Replace NA with "violation"

utilization$TimeSegment <- factor(utilization$TimeSegment)

utilization <- utilization %>%
  mutate(ViolationType = ifelse(ViolationType == "", "booking", ViolationType)) 

```

```{r}
# dwell time - min
grid.arrange(
ggplot(utilization, aes(x = DwellTimeMinutes)) + geom_histogram(bins = 20, fill = "#440154", color = "white") +
  labs(title = "Dwell Time Distribution", x = "Dwell Time (minutes)", y = "Frequency")+
  theme_minimal(),

ggplot(utilization, aes(x = TimeSegment)) +
  geom_bar(fill = "#440154", color = "white") + 
  theme_minimal() + 
  labs(title = "Counts by Time Segment", x = "Time Segment", y = "Count") + 
  theme_minimal(),

# vehicle type:commercial/medium commercial/other/truck
ggplot(utilization, aes(x = VehicleType)) + geom_bar(fill = "#440154") +
  labs(title = "Vehicle Type Distribution", x = "Vehicle Type", y = "Count")+
  theme_minimal(),

# vehicle type: car/freight/truck/van
ggplot(utilization, aes(x = EventType)) + geom_bar(fill = "#440154") +
  labs(title = "Event Type Distribution", x = "Event Type", y = "Count")+
  theme_minimal(),
nrow=2)

```

```{r}
# Availability of curb zones
# vehicle count by curb zone and tiem segment
availability_analysis <- utilization %>%
  group_by(OMFCurbZoneID, TimeSegment) %>%
  summarise(VehicleCount = n())

ggplot(availability_analysis, aes(x = OMFCurbZoneID, y = VehicleCount, fill = TimeSegment)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_manual(values = palette6)+
  labs(title = "Vehicle Count by Curb Zone and Time Segment", x = "Curb Zone ID", y = "Vehicle Count")

# violation type distribution by curb zone
violation_analysis <- utilization %>%
  group_by(OMFCurbZoneID, ViolationType) %>%
  summarise(Count = n())

ggplot(violation_analysis, aes(x = OMFCurbZoneID, y = Count, fill = ViolationType)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_manual(values = palette6)+
  labs(title = "Violation Type Distribution by Curb Zone", x = "Curb Zone ID", y = "Count")

```

```{r}
utilization_sf <- st_as_sf(utilization, wkt = "geometry", crs = 4326)

# distribution of Curb Zones
ggplot() +
  annotation_map_tile(zoom = 12) +  # Adjust the zoom level as needed
  geom_sf(data = utilization_sf, aes(color = TimeSegment), size = 0.7) +
  scale_fill_manual(values = palette6)+
  labs(title = "Spatial Distribution of Curb Zones in Philadelphia", x = "Longitude", y = "Latitude") +
  theme_minimal()

```

### event data exploratory analysis
```{r id_clean, include=FALSE}
event_export$curb_zone_id <- substr(event_export$curb_zone_id, nchar(event_export$curb_zone_id)-2, nchar(event_export$curb_zone_id))

event_export$event_session_id <- substr(event_export$event_session_id, nchar(event_export$event_session_id)-3, nchar(event_export$event_session_id))
```

```{r time_clean, echo=TRUE}
# Correctly convert the timestamps from milliseconds to POSIXct
event_export$event_time_start = as.POSIXct(event_export$event_time_start / 1000, origin="1970-01-01", tz="UTC")
event_export$event_time_end = as.POSIXct(event_export$event_time_end / 1000, origin="1970-01-01", tz="UTC")

# Calculate dwell time in seconds
event_export$dwell_time = difftime(event_export$event_time_end, event_export$event_time_start)

# Convert the dwell time to minutes
event_export$dwell_time_minutes = as.numeric(event_export$dwell_time, units = "mins")
event_export$dwell_time_minutes <- round(event_export$dwell_time_minutes,2)

# Add time series data
event_export$event_time_start <- as.POSIXct(event_export$event_time_start, format = "%Y-%m-%d %H:%M:%S")
event_export <- event_export%>%
  mutate(Date=as.Date(event_time_start),
         week=week(Date),
         dotw=wday(Date,label=TRUE),
         interval60=floor_date(event_time_start,unit ="hour"),
         interval15=floor_date(event_time_start,unit="15 mins"),
         time_of_day=case_when(hour(interval60)<7 | hour(interval60)>19 ~ "overnight",
                               hour(interval60)>=7 & hour(interval60)<10 ~ "AM Rush",
                               hour(interval60)>=10 & hour(interval60)<15 ~ "Mid Day",
                               hour(interval60)>=15 & hour(interval60)<=19 ~ "PM Rush"),
         weekend=ifelse(dotw %in% c('Sun','Sat'),'Weekend','Weekday'))

head(event_export)
```

```{r exploratory_analysis_curb}
#curb utilization rates
utilization_rates <- event_export %>%
  group_by(curb_zone_id) %>%
  summarise(Total_Events = n(),
            Total_Dwell_Time = sum(dwell_time_minutes),
            Average_Dwell_Time = mean(dwell_time_minutes))

plot1 <- ggplot(utilization_rates,aes(x=curb_zone_id,y=Total_Events))+
  geom_bar(stat="identity",fill="#3E4A89")+
  theme_minimal()+
  labs(x="Curb Zone ID", y = "Total Events", title="Total Events by Curb Zone")
plot2 <- ggplot(utilization_rates,aes(x=curb_zone_id,y=Total_Dwell_Time))+
  geom_bar(stat="identity",fill="#1F9E89")+
  theme_minimal()+
  labs(x="Curb Zone ID", y = "Total Events", title="Total Dwell Time by Curb Zone")
plot3 <- ggplot(utilization_rates,aes(x=curb_zone_id,y=Average_Dwell_Time))+
  geom_bar(stat="identity",fill="#35B779")+
  theme_minimal()+
  labs(x="Curb Zone ID", y = "Average Dwell Time", title="Average Dwell Time by Curb Zone")

grid.arrange(plot1,plot2,plot3,nrow=3)
```

```{r exploratory_serial}
#peak parking times
event_export$event_time_start <- as.POSIXct(event_export$event_time_start, format = "%Y-%m-%d %H:%M:%S")
peak_times <- event_export%>%
  mutate(Hour = format(event_time_start, "%H")) %>%
  group_by(Hour) %>%
  summarise(Events = n())

#event patterns over time
patterns <- event_export %>%
  group_by(Date=as.Date(event_time_start)) %>%
  summarise(Events=n()) %>%
  mutate(week=week(Date),
         dotw=wday(Date,label=TRUE))

byhour <- event_export %>%
  group_by(time_of_day) %>%
  summarise(Events=n())

byweekend<- event_export %>%
  group_by(weekend) %>%
  summarise(Events=n())

weekend_hour <- event_export %>%
  group_by(weekend, hour(interval60)) %>%
  summarize(Events=n()) %>%
  rename(hour='hour(interval60)')

  grid.arrange(
  ggplot(patterns, aes(Date,Events)) + geom_line(color="#1F9E89") + 
    labs(title="Event Patterns by Time, from Oct 2022 to Apr 2023", x="Date", y="Event Counts") + theme_minimal(),
   ggplot(patterns, aes(dotw,Events)) + geom_bar(stat="identity",fill="#1F9E89") + 
    labs(title="Event Patterns by Day of the Week, from Oct 2022 to Apr 2023", x="Date", y="Event Counts") + theme_minimal(),
  ggplot(peak_times,aes(x=Hour,y=Events))+
  geom_bar(stat="identity",fill="#1F9E89")+
  theme_minimal()+
  labs(x="Hour", y = "Events", title="Events by Hour of the Day"),
  ggplot(byhour, aes(time_of_day,Events)) + geom_bar(stat="identity",fill="#1F9E89") + 
    labs(title="Event Patterns by Hour of the Day", x="Hour", y="Event Counts") + theme_minimal(),
  ggplot(byweekend, aes(weekend,Events)) + geom_bar(stat="identity",fill="#1F9E89") + 
    labs(title="Event Patterns by Weekend vs Weekday", x="Weekend or Weekday", y="Event Counts") + theme_minimal(),
  ggplot(weekend_hour, aes(x=hour, y=Events, color=weekend)) + geom_line() + 
    scale_color_manual(values=palette2)+
    labs(title="Event Patterns under Week and Time", x="Hour", y="Event Counts") + theme_minimal(),
  nrow=3)
   
  #Correlation
  correlation <- cor(event_export$dwell_time_minutes,event_export$vehicle_length)
```

```{r exploratory_operation}
#parking duration distribution

#vehicle type analysis
vehicle_type <- event_export %>%
  group_by(vehicle_type) %>%
  summarise(Total_Events=n())

grid.arrange(
ggplot(event_export, aes(x=dwell_time_minutes)) +
  geom_histogram(binwidth = 5,fill="#FDE725",color="white") +
  theme_minimal()+
  labs(x="Dwell Time (minutes)", y="Count", title="Parking Duration Distribution"),
ggplot(vehicle_type,aes(x=vehicle_type,y=Total_Events))+
  geom_bar(stat="identity",fill="#FDE725")+
  theme_minimal()+
  labs(x="Vehicle Type", y = "Events", title="Events by Vehicle Type")+
  theme_minimal(),
nrow=2)
```

```{r}

```